@host=http://localhost:5190

GET {{host}}/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlN2Y4MmQxZC05OTdiLTRmNWUtOWU1MC01MWRlY2FhNTI4YTMiLCJnaXZlbl9uYW1lIjoiRm5hbWUiLCJmYW1pbHlfbmFtZSI6IkxOQU1FIiwianRpIjoiMmM1Y2Y0MGYtYzk4ZC00M2U1LWE0ZjMtYjJlZTJmYmEzMDlkIiwiZXhwIjoxNjk5OTYyNzc4LCJpc3MiOiJPbWVnYVNvZnQubWEiLCJhdWQiOiJPbWVnYVNvZnQubWEifQ.lGU1v9VgAXXEouBeNPsXGKt6Y6_8y2tHmt0JrWlzhMw